name: Build PDF 1 complete volume

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Print start date
      run: date +%Y-%m-%d_%H:%M

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1 # 0 if you want to push to repo

    - name: Python set up
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

#    - name: setup environment to DE lang
#      run: |
#        cd /usr/share/locales
#        sudo ./install-language-pack de_DE.UTF-8

    - name: Test ls before
      run: |
        pwd
        ls -l

    - name: Check chapters for known issues
      run: python3 scripts/check-chapters.py

    - name: Install requirements
      run: |
        # sudo apt update > /dev/null
        sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Print versions
      run: |
        cat /etc/os-release
        xelatex -v
        latexmk -v
        # pandoc -v
        python3 --version

    - name: Make PDF
#      run: sh scripts/make_pdf-1-vol.sh > /dev/null
      run: latexmk hpmor > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: |
          ./hpmor*.pdf

    - name: Print end date
      run: date +%Y-%m-%d_%H:%M
