name: Build PDF all parallel

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  hpmor:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install requirements
      run: |
        sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Make PDF
      run: latexmk hpmor > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor.pdf

  hpmor-1:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install requirements
      run: |
        sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Make PDF
      run: latexmk hpmor-1 > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-1.pdf

  hpmor-2:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Make PDF
      run: latexmk hpmor-2 > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-2.pdf

  hpmor-3:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Make PDF
      run: latexmk hpmor-3 > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-3.pdf

  hpmor-4:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Make PDF
      run: latexmk hpmor-4 > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-4.pdf

  hpmor-5:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Make PDF
      run: latexmk hpmor-5 > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-5.pdf

  hpmor-6:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: Make PDF
      run: latexmk hpmor-6 > /dev/null

    - name: Publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-6.pdf
